### ISSUE TITLE
Deploy issue when Webhook is triggered via PR merge.

### ISSUE THREAD

**Issue by dctoon** [auth0-extensions/auth0-visualstudio-deploy#13] opened 2017-06-08 08:45 UTC
When a PR is merged into a lets say the _master_ branch, a Web Hook (Code Pushed) is triggered by VSTS. Apparently the payload of the Web Hook is different between a regular Code Push and a merge of a PR, and this results in the error `Unhandled rejection TypeError: Cannot read property 'forEach' of undefined`. The missing piece of data that is missing in the PR payload is the property `resource.commits`.

Structure of a regular commit

```
{
    ...
    "resource": {
        "commits": [
            {
                "commitId": "6497fd0250b5e5a03a0f6737cf89d07c3a860dfd",
                "author": { "name": "Toon De Coninck", ... },
                "committer": { "name": "Toon De Coninck", ... },
                "comment": "Updated log-to-console.js",
                "url": "https://xxxxx.visualstudio.com/_apis/git/repositories/xxx/commits/6497fd0250b5e5a03a0f6737cf89d07c3a860dfd"
            }
        ],
        "refUpdates": [{ ... }],
        "repository": { ...},
        "pushedBy": { ... },
        "pushId": 45,
        "date": "2017-06-08T08:20:23.9782207Z",
        "url": "https://xxx.visualstudio.com/_apis/git/repositories/xxx/pushes/45"
    },
    "resourceVersion": "1.0",
    ...
}

```

Structure of the payload but when merging a PR.

```
{
    ...
    "resource": {
      // Notice no Commits array here
        "refUpdates": [{ ... }],
        "repository": { ...},
        "pushedBy": { ... },
        "pushId": 45,
        "date": "2017-06-08T08:20:23.9782207Z",
        "url": "https://xxx.visualstudio.com/_apis/git/repositories/xxx/pushes/45"
    },
    "resourceVersion": "1.0",
    ...
}
```

As a second thought, this could also be an issue on the VSTS platform as well (https://www.visualstudio.com/en-us/docs/integrate/get-started/service-hooks/events#code-pushed)

**Comment by dctoon** [comment] 2017-07-07 14:18
The linked PR to this issue did not fixed the issue. The call to VSTS API `getPushCommits ` does not return `commits` when the `Code pushed` event is trigger by VSTS when a PR is merged. So the deploy request results in this response https://github.com/auth0-extensions/auth0-visualstudio-deploy/blob/master/server/routes/webhooks.js#L55

So a possible solution would be to create a new Service Hook in VSTS of event type `Pull request merge commit created`, that event will return in the payload the property `pullRequestId` this can be used as a parameter to call the VSTS API method [getPullRequestCommits](https://www.visualstudio.com/en-us/docs/integrate/extensions/reference/client/api/tfs/versioncontrol/gitrestclient/githttpclient2_1#method_getPullRequestCommits). This call will return the list of commits, and not an empty array.

**Comment by sgmeyer** [comment] 2017-07-07 14:57
@dctoon thanks for the info.  I'll take a dive into this now to see what we can do to get this working.

**Comment by sgmeyer** [comment] 2017-07-07 17:39
@dctoon seems the issue is around getPushCommits.  The event being sent by the TFS webhook is of type `git.push`.  When this event is being called for a PullRequest the commits array is either empty or undefined.  I think what we need to do is send a second event `git.pullrequest.merged`.  Then with this we'll need to either pull the commits directly off the event request or have the code call `getPullRequestCommits`.  I am working on a fix now.

**Comment by sgmeyer** [comment] 2017-08-14 12:50
This has been resolved and deployed.

**Closed as completed by sgmeyer** 2017-08-14 12:50 UTC
